apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: backend
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value: simpletest-agent.observability.svc.cluster.local
        image: srishtiguleria/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - name: backendport
          containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
