apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8001
      targetPort: backendport
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: trial-nodeport
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - port: 8002
      targetPort: trialport
      nodePort: 30082
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8000
      targetPort: frontendport
      nodePort: 30080
  type: NodePort
